name = "rolldoradocasino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradocasino.pt"
HMAC_KEY = "3485c1721176bec8e45777bb546270eaaef40ab5c31c9a891d8f9e68a7e229b8"
COOKIE_NAME = "wo4"
PLAY_PATH = "visit-site"
BUTTON_ID = "p8bcd9d39fed955f0eae1357187aaab82"
GATE_SALT = "6781d3c1a4422c2a"
